name: Continuous Delivery

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3  # Atualize para a vers達o mais recente

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Atualize para a vers達o mais recente

      - name: Log in to registry
        uses: docker/login-action@v3  # Atualize para a vers達o mais recente
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4  # Atualize para a vers達o mais recente
        with:
          push: true
          tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agendamento-coleta:${{ github.sha }}  # Remova a barra inicial
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiap-agendamento-contato-dev'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agendamento-coleta:${{ github.sha }}'
